lenguyenthanh/fide

- TODO.md
- modules/backend/src/main/scala/service.player.scala
- modules/db/src/main/scala/Db.scala
- modules/db/src/test/scala/DbSuite.scala
- modules/domain/src/main/scala/Models.scala
- modules/smithy/src/main/smithy/_global.smithy
- modules/smithy/src/main/smithy/players.smithy
- Filter by rating (min, max) for {standard, rapid, blizt)
- Filter by isActive
> Support filter query

- modules/backend/src/main/scala/app.resources.scala
- modules/crawler/src/main/scala/Crawler.scala
- modules/crawler/src/main/scala/UpdateChecker.scala
- modules/db/src/main/resources/db/migration/V0002__cache_table.sql
- modules/db/src/main/scala/Store.scala
- modules/db/src/test/scala/Containers.scala
- modules/db/src/test/scala/DbSuite.scala
- modules/db/src/test/scala/StoreSuite.scala
Apparently FIDE website show the last update time for their players
database like this `(02 Apr 2024, Sz: 10.11 MB)`. So, this pr is to
add the ability to the `Crawler` to  use that timestamp to decide
it should fetch the data or not.
> Smarter crawler

- TODO.md
- modules/backend/src/main/scala/service.player.scala
- modules/smithy/src/main/smithy/_global.smithy
- modules/smithy/src/main/smithy/players.smithy
Use smithy's [constraint traits](https://smithy.io/2.0/spec/constraint-traits.html) to sanitize our input/output. This PR adds:
- Constraint `Rating` filter in range from 1 to 4000 (to be safe)
- Constraint paging input to be natural number
- Constraint page Size in range from 1 to 100
> Use more Smithy constraint trait

- modules/crawler/src/main/scala/Crawler.scala
- modules/db/src/main/resources/db/migration/V0007__rename_players_birth_year.sql
- modules/db/src/main/scala/Db.scala
- modules/domain/src/main/scala/Domain.scala
- modules/smithy/src/main/smithy/_global.smithy
and year to birth_year in players table
> Rename year to birthYear

- build.sbt
- modules/backend/src/main/scala/service.player.scala
- modules/smithy/src/main/scala/types.scala
- modules/smithy/src/main/smithy/_global.smithy
- modules/smithy/src/main/smithy/players.smithy
This PR sets default for `pageSize`, and use type refinement for `page`
> Refinement types for paging

- modules/db/src/main/resources/db/migration/V0001__init.sql
- modules/domain/src/main/scala/Domain.scala
- modules/smithy/src/main/smithy/_global.smithy
I think we can clean up what will never be used
> FIDE never say national title

- modules/crawler/src/main/scala/Crawler.scala
- project/Dependencies.scala
Crawler is uncancellable. This PR is to fix it.
Related to https://github.com/lhns/fs2-compress/issues/113
> Use fs2-decompress zip4j module

- modules/backend/src/main/scala/service.federation.scala
- modules/backend/src/main/scala/service.player.scala
- modules/smithy/src/main/smithy/_global.smithy
- modules/smithy/src/main/smithy/federations.smithy
- modules/smithy/src/main/smithy/health.smithy
- modules/smithy/src/main/smithy/players.smithy
https://smithy.io/2.0/spec/idl.html#inline-input-output-shapes
Close #96
> Use inline inputs/outputs for smithy spec

- modules/domain/src/main/scala/Domain.scala
This reverts commit 50ac307cf65eaaf15918b0f075960f67b839d585.
> Revert ""NON FEDERATION""

- build.sbt
- modules/api/src/main/scala/types.scala
- modules/api/src/main/smithy/_global.smithy
- modules/api/src/main/smithy/federations.smithy
- modules/api/src/main/smithy/players.smithy
- modules/types/src/main/scala/Natural.scala
The idea is We can use those refinement types across all modules
> Try to move refinement types to their own modules

- modules/api/src/main/scala/providers.scala
- modules/api/src/main/smithy/_global.smithy
- modules/api/src/main/smithy/federations.smithy
- modules/api/src/main/smithy/players.smithy
- modules/backend/src/main/scala/service.player.scala
- modules/types/src/main/scala/NonEmptySet.scala
> Add config to limit max number of ids for getPlayersWithIds api

- modules/backend/src/main/scala/service.federation.scala
- modules/backend/src/main/scala/service.player.scala
- modules/db/src/main/scala/Db.scala
- modules/db/src/test/scala/DbSuite.scala
- modules/domain/src/main/scala/Models.scala
> Support searchByName in Db.allPlayers

- modules/backend/src/main/scala/service.player.scala
I forgot to put name into the filter
> Fix search players by names

- modules/api/src/main/smithy/_global.smithy
- modules/backend/src/main/scala/service.federation.scala
- modules/backend/src/main/scala/service.player.scala
- modules/db/src/main/scala/Db.scala
- modules/domain/src/main/scala/Models.scala
And fix SqlSyntax error when involving and query
> Implement filter players by titles

- modules/crawler/src/main/scala/Downloader.scala
- modules/crawler/src/test/scala/ParserTest.scala
fix https://github.com/lenguyenthanh/fide/issues/250
> inactive only if includes `i`

- modules/crawler/src/test/scala/ParserTest.scala
- modules/types/src/main/scala/Rating.scala
fix https://github.com/lenguyenthanh/fide/issues/253
> Filter out rating that lower than 1400

- modules/crawler/src/main/scala/Downloader.scala
- modules/crawler/src/test/scala/ParserTest.scala
Fix https://github.com/lenguyenthanh/fide/issues/34
> Sanitize players's name

- modules/crawler/src/main/scala/Syncer.scala
It's easy to understand why this functionally equal, but I am lazy right now to prove it 😁
> Golf: use as

- modules/crawler/src/test/scala/ParserTest.scala
- modules/db/src/main/scala/Db.scala
- modules/domain/src/main/scala/Domain.scala
I've not changed `flatMap`s from `Option` to `Option`, only from `List`s
> Golf: mapFilter

- modules/api/src/main/smithy/_global.smithy
- modules/backend/src/main/scala/service.federation.scala
- modules/backend/src/main/scala/service.player.scala
- modules/backend/src/test/scala/Arbitraries.scala
- modules/db/src/main/scala/Db.scala
- modules/domain/src/main/scala/Models.scala
> Add has_{title, women_title, other_titles} filter

- modules/api/src/main/smithy/federations.smithy
- modules/api/src/main/smithy/players.smithy
- modules/backend/src/main/scala/service.federation.scala
- modules/backend/src/main/scala/service.player.scala
- modules/db/src/main/scala/Db.scala
- modules/db/src/test/scala/DbSuite.scala
> Add total_records fields for players and federations endpoint

- build.sbt
- modules/backend/src/main/scala/app.config.scala
- modules/backend/src/test/scala/DbIntegrationSuite.scala
- modules/db/src/main/scala/config.scala
- modules/db/src/test/scala/Containers.scala
- project/Dependencies.scala
> Use refinement type for config

- modules/crawler/src/main/scala/Downloader.scala
Fix `2025-03-24 23:42:00,198 [io-compute-8] WARN fide.App - Unkown federation: Ind for player: 5010179`
> Federation id may not be all caps
